# Generated by Django 2.2.8 on 2020-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message', models.CharField(default='na', max_length=255)),
                ('message_type', models.CharField(default='na', max_length=100)),
                ('media_url', models.CharField(default='na', max_length=255)),
                ('sent_at', models.TimeField(auto_now_add=True)),
                ('last_modified', models.TimeField(auto_now=True)),
            ],
        ),
    ]
