# Generated by Django 2.2.8 on 2020-01-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ken_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message_type',
            new_name='action',
        ),
    ]
