# Generated by Django 2.2.8 on 2020-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ken_chat_app', '0002_auto_20200127_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sent_at',
            new_name='timestamp',
        ),
    ]
