# Generated by Django 2.2.8 on 2020-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ken_chat_app', '0003_auto_20200130_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.CharField(default='na', max_length=255),
        ),
    ]
