# Generated by Django 2.2.8 on 2020-01-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ken_chat_app', '0004_auto_20200130_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='last_modified',
        ),
    ]
